language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

git:
  depth: 1

notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.10.2

script:
  - golangci-lint run
  - go test -v -race ./...
